# This is a basic workflow to help you get started with Actions

name: Fg Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,Dev ]
  pull_request:
    branches: [ master,Dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

# Build the application
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
 
 # upload apk name and download build artifact apk should be same (32,39)
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
         name: app
         path: app/build/outputs/apk/debug/app-debug.apk
  
# Download a Build Artifact
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.8
      with:
          name: app
          path: ${{github.workspace}}/signedrelease  
  
  App_Center_Deploy:
      name: app center deploy
      runs-on: ubuntu-latest
      environment: 
        name: Development
      if: github.ref == 'refs/heads/Dev'
      needs: [build]
      
      steps:
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
         appName: ${{secrets.APP_CENTER_APPNAME}}
         token: ${{secrets.APP_CENTER_TOKEN}}
         group: ${{secrets.APP_CENTER_GROUP}}
         file: ${{github.workspace}}/signedrelease/app-debug.apk
         notifyTesters: true
         debug: false
      
  Playstore_Deploy:
      name: playstore deploy
      runs-on: ubuntu-latest
      environment: 
        name: Production
      needs: [build]  
      
      steps:      
      
      - name: upload release to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
         packageName: ${{ secrets.PACKAGE_NAME }}
         releaseFiles: /home/runner/work/NBDashboard/NBDashboard/signedrelease/app-release-signed.apk
         track: beta
         inAppUpdatePriority: 2
         userFraction: 0.33  
